### ISSUE TITLE
Support for other (Adafruit) touchscreens

### ISSUE THREAD

**Issue by nift4** [nift4/pigame#4] opened 2019-01-25 19:44 UTC
The 2.8" Resistive and other touch screens need a old version of SDL. If this driver supports them we don't have to install very old software. But I don't have them. I only maintain 2.8" capacitive. But any help or pull requests are okay and probally accepted.

**Comment by BroMarduk** [comment] 2019-01-28 13:58
Let me know how you wish to support resistive touchscreens in your code.   

It will require both a change in pitft_touchscreen and pigame as the events are different on the Adafruit Restive touch screens in EVDEV.   I have this working in a fork of @PrzemoF's pitft_touchscreen - I don't know if he cares about resistive screen support in his code, but if he is responsive to the idea I will see about a PR to bring this code into the project.  I'm currently testing the SYN_DROPPED message support that SHOULD be in pitft_touchscreen regardless if the resistive support is added or not.

Device detection could be done somewhat automatically by looking at the device.name property of the evdev driver or manually specified by a switch (or both!).  May require some coordination :).

**Comment by nift4** [comment] 2019-01-28 16:16
I'm intrested and I have a fork of pitft_touchscreen that is linked on my pages so we can test and release some resistive touchscreen supporting versions :+1:

**Comment by BroMarduk** [comment] 2019-01-30 17:16
I created a PR to get the code fully inline with what is in the base repository.   Once that gets merged in I'll create the resistive support - you might want to create a separate branch in the pitft_touchscreen project until we get everything synced.  I've tested the resistive support and it works with all the PiTFT resistive screens I have (2.4, 2.8, 3.2 and 3.5).   I have the older versions (the ones with the 20 pin connectors) that I still want to test as well as some of the 4D Systems displays that I have around.

Also working on getting it running on Pimoroni HyperPixel 3.5 and 4.0 screens.  The HyperPixel supports multi-touch, so I'm trying to understand fully how EVDEV uses the SLOT messages - I understand for normal operation, but it gets tricky when adding SYN_DROPPED support.  The Pimoroni drivers are also doing some strange X,Y stuff I need to get to the bottom of and have some issues with Stretch support.  Not to mention the resolution is 800x1024.  So this is down the road a bit. :)

**Comment by nift4** [comment] 2019-01-30 18:15
Cool!

**Comment by BroMarduk** [comment] 2019-02-01 16:36
I think I am going to make the touchscreen a parameter to the PiTft init method.

- That still allows the user to override the autodetected device if they need to for any reason.
- For now, keep the 2.8 Capacitive Adafruit screen as the default, but this may be a future breaking change as if more screens are supported a default seems less than optimal.
- I wanted to base autodetection on the evdev device capabilites but the issue is its complicated to determine due to the lack of information passed into evdev.  Not all device drivers/overlays are built the same way and some seem to leave out important information (like resolution).
- Another option is to base autodetection off the loaded dtoverlay of known types. For some (probably good but not for me) reason if you load a dtoverlay in /boot/config.txt it does not appear when the dtoverlay -l command is issued, so the only way I can find right now is to  parse /boot/config.txt and that itself seems clunky and error prone not to mention there are multiple configurations of the overlays based on the version of the overlay.


If adding the device in the __init__ is OK with you, I will add this code in which will allow resistive support.

Other items I can add fairly easily that I think we should
- Portrait support (0 and 180 rotations) as I have this working but not fully tested (and something that I will require in my main app)
- Support for axis swaps and inversions.  Probably via parameters, but there are reasons (usually other apps) that sometimes require these and many display overlays support them.   This was something that @goose2000 brought to my attention in the other test project.

Other items that I would like to see added
- Separation of the button code from the touchscreen code or at least make it not the default.

Would like to hear your thoughts @nift4 ....

**Comment by nift4** [comment] 2019-02-01 19:39
I'm okay with all changes in your comment, for the button code updates are coming from mine side soon.

**Comment by nift4** [comment] 2019-02-01 19:49
@BroMarduk #13 for the buttons :)

**Comment by nift4** [comment] 2019-03-10 14:11
@BroMarduk Any progress?

**Comment by BroMarduk** [comment] 2019-03-11 19:58
Yes, I have had it working on all PiTFT screens from Adafruit that support touch (resistive and capacitive) in both portrait and landscape mode.   I now have to fix my code so it supports the different nuances for each screen as the axes are in different states depending on the screen type and rotation.

I may do a release with just landscape to start then add in portrait down the road.   I know it all works, now just have to tie it all together.

**Comment by nift4** [comment] 2019-03-12 14:49
@BroMarduk Thanks for your work! :)

**Comment by nift4** [comment] 2019-05-18 20:36
@BroMarduk Any news?

**Comment by nift4** [comment] 2019-12-22 16:40
@BroMarduk Anything on this?

**Closed as completed** 2021-11-06 15:30 UTC
Labels: enhancement, help wanted, good first issue
